main:
  - name: "사업 소개 | INTRODUCTION"
    url: "/introduction/"
    weight: 10

  - name: "구성원 | MEMBERS"
    url: "/members/member/"
    weight: 20

  - name: "연구 | RESEARCH"
    url: "/research/"
    weight: 30

  # 활동 | OUTCOMES 부모 메뉴
  - name: "활동 | OUTCOMES"
    url: "/outcomes/"
    identifier: outcomes
    weight: 40

  - name: "지진방재마이크로전공 개설"
    parent: outcomes
    url: "/outcomes/major/"
    weight: 2

  - name: "외부전문가 특강"
    parent: outcomes
    url: "/outcomes/lectures/"
    weight: 3

  - name: "학술발표"
    parent: outcomes
    url: "/outcomes/conference-papers/"
    weight: 4

  - name: "홍보용 배너전시"
    parent: outcomes
    url: "/outcomes/exhibition/"
    weight: 5
  # --- 활동 | OUTCOMES 그룹 끝 ---

  # --- 장비 소개 | INSTRUMENT 그룹 시작 ---
  - name: "장비 소개 | INSTRUMENT"
    url: "/instrument/"
    identifier: instrument
    weight: 50

  - name: "소프트웨어"
    parent: instrument
    url: "/instrument/software/"
    weight: 1

  - name: "실물장비"
    parent: instrument
    url: "/instrument/hardware/"
    weight: 2
  # --- 장비 소개 | INSTRUMENT 그룹 끝 ---

  - name: "게시판 | BOARD"
    url: "/post/"
    weight: 60
