# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: "사업 소개 | INTRODUCTION"
    url: "/#introduction" 
    weight: 10
  - name: "구성원 | MEMBERS"
    url: "/#members"
    weight: 20
  - name: "연구 | RESEARCH"
    url: "/#research"
    weight: 30 
  - name: "이력사항 | PUBLICATION"
    url: "/#publication"
    weight: 40
  - name: "장비 소개 | INSTRUMENT"
    url: "/#instrument"
    weight: 50
  - name: "게시판 | BOARD"
    url: "/#board"
    weight: 60
